provider "google" {
  project     = "mikubon"
  region      = "us-central1"

}

# GKE Cluster
resource "google_container_cluster" "gke_cluster" {
  name     = "gke-cc"
  location = "us-central1-c"

  initial_node_count = 1

  node_config {
    machine_type = "e2-micro"
    disk_size_gb = 10
  }
  deletion_protection = false

}

# Source Repository
resource "google_sourcerepo_repository" "node-service-repo-1" {
  name = "node-service-repo-1"
}

# Build Trigger
resource "google_cloudbuild_trigger" "node-service-trigger-1" {
  name     = "node-service-trigger-1"
  description = "Trigger for Cloud Source Repository repo-1"
  location = "us-central1"

  trigger_template {
    project_id = "mikubon"
    repo_name  = google_sourcerepo_repository.node-service-repo-1.name
    branch_name = "^main$"
 }
  service_account = "projects/mikubon/serviceAccounts/63267194612-compute@developer.gserviceaccount.com"
  filename = "cloud-build/cloudbuild.yaml"
}

# Source Repository
resource "google_sourcerepo_repository" "node-service-repo-2" {
  name = "node-service-repo-2"
}

# Build Trigger
resource "google_cloudbuild_trigger" "node-service-trigger-2" {
  name     = "node-service-trigger-2"
  description = "Trigger for Cloud Source Repository repo 2"
  location = "us-central1"

  trigger_template {
    project_id = "mikubon"
    repo_name  = google_sourcerepo_repository.node-service-repo-2.name
    branch_name = "^main$"
 }
  service_account = "projects/mikubon/serviceAccounts/63267194612-compute@developer.gserviceaccount.com"
  filename = "cloud-build/cloudbuild.yaml"
}

# Artifact Registry
resource "google_artifact_registry_repository" "node-server-repo" {
  location      = "us-central1"
  repository_id = "node-server-repo"
  description   = "Artifact repository to store node docker images generated by Cloud Build"
  format        = "DOCKER"
}

# Compute Disk
resource "google_compute_disk" "shared-disk" {
  name  = "shared-disk-tf"
  type  = "pd-standard"
  zone  = "us-central1-c"
  size = "1"
  labels = {
    environment = "dev"
  }
}